const run = async () => {
  console.log("Running..");
};

run().catch((error) => console.error(error));
